### ISSUE TITLE
Intro Example should not be broken

### ISSUE THREAD

**Issue by frol** [Aslemammad/vitext#10]
I tried intro example and bumped into a few problems:

1. vitext 0.0.1 is deleted, so I had to update it to `0.0.2` in the `intro/package.json`
2. next, `npm run dev` failed to start due to: `Error: Cannot find module 'react-refresh/cjs/react-refresh-runtime.development.js'`. I Resolved it with `npm add -D react-refresh`
3. next, while `npm run dev` brought the server up and running, it does not work well ("increase" and "decrease" buttons do not work), and I see the following error in the terminal, if that helps:
  ![image](https://user-images.githubusercontent.com/304265/128640439-6d06cc50-8011-4b58-bff1-647c5af93095.png)

Environment:
* Arch Linux, x86-64
* node.js 16.6.1
* npm 7.20.5
* vitext example from master branch

P.S. Cool project! :+1:

**Comment by Aslemammad** [comment]
Thank you @frol, That's really helpful. I'll fix it soon.

**Comment by Aslemammad** [comment]
@frol Could you share a simple reproduction?

**Comment by Aslemammad** [comment]
Hey @frol, How are you doing?
Sorry for the late response; I was infected by covid.
I pushed #13, check out the new release & see if it works for you!

**Comment by frol** [comment]
@Aslemammad Hey! I hope you are doing well now :pray: 

I tried it again:

```
$ git clone https://github.com/Aslemammad/vitext.git
$ cd vitext/packages/examples/intro
$ npm install
$ npm run dev
```

![image](https://user-images.githubusercontent.com/304265/131667305-9852c68d-4491-41e5-8155-a97b1679fce7.png)

```
$ npm install tslib
$ npm run dev
```

Open the browser and see the same (or very similar error):

![image](https://user-images.githubusercontent.com/304265/131667369-1efa4bf4-0c3b-4c29-8d0e-7e7f804eb305.png)

```
$ node --version
v16.8.0
$ uname -a
Linux ram 5.13.13-arch1-1 #1 SMP PREEMPT Thu, 26 Aug 2021 19:14:36 +0000 x86_64 GNU/Linux
```

Still does not work for me

**Comment by Aslemammad** [comment]
OH, I think you need to do `yarn install` on the root (`vitext` dir & not `vitext/packages/vitext`) first because it's a yarn monorepo!

**Comment by frol** [comment]
Still does not work:

```
$ git clone https://github.com/Aslemammad/vitext.git
$ cd vitext
$ yarn
```

![image](https://user-images.githubusercontent.com/304265/131817265-f5827b4d-7ca0-4787-976b-b2e5399a61b1.png)

![image](https://user-images.githubusercontent.com/304265/131817351-2cff9504-cde1-44c6-9077-6fc10efaeb47.png)

```
$ yarn run dev
```

![image](https://user-images.githubusercontent.com/304265/131817480-4ee1f69a-8670-4d26-afa8-8e55320594f0.png)

**Comment by Aslemammad** [comment]
That's really weird!
Since I cannot reproduce the error, could you debug it if you're interested?
You need to check the `resolveId/load` functions in the `plugin.ts` files.

BTW, why does the error shows `import p from './@vitext/_app'? because I changed it from a simple import to a dynamic import in the latest release! [Link](https://github.com/Aslemammad/vitext/blob/master/packages/vitext/src/client/main.tsx#L16)

**Comment by frol** [comment]
@Aslemammad Here is the Dockerfile to reporduce the issue:

```Dockerfile
FROM node

RUN git clone https://github.com/Aslemammad/vitext.git
RUN cd vitext && \
    yarn && \
    cd packages/examples/intro && \
    yarn

WORKDIR /vitext/packages/examples/intro
CMD ["yarn", "dev", "--host"]
```

```
$ docker build --tag vitext-intro-example
$ docker run -it --rm -p 3000:3000 vitext-intro-example
```
